In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4])

In [3]:
print(a1)
print(a1.shape)

[1 2 3 4]
(4,)


In [4]:
a1[0]

1

In [5]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])

In [6]:
print(a2)
print(a2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [7]:
a3 = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])

In [8]:
print(a3)
print(a3.shape)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
(2, 2, 4)


In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.full(5, 3)

array([3, 3, 3, 3, 3])

In [16]:
a1

array([1, 2, 3, 4])

In [17]:
print(a1[:1])
print(a1[-1])
print(a1[1:3])
print(a1[1:])
print(a1[a1>2])

[1]
4
[2 3]
[2 3 4]
[3 4]


In [19]:
print(a2[0]) # row 1
print(a2[0,:]) # row 1, every column
print(a2[0:1,:]) # row 1, every column
print(a2[0:3,:]) # row 1~3, every column
print(a2[0:2, 1:3]) # row 1~2, column 2~3
print(a2[-1,1:]) # last row, column 2~end
print(a2[a2>2]) # all elements > 2, 1d-array

[1 2 3 4]
[1 2 3 4]
[[1 2 3 4]]
[[1 2 3 4]
 [5 6 7 8]]
[[2 3]
 [6 7]]
[6 7 8]
[3 4 5 6 7 8]


In [20]:
x = np.random.choice(np.arange(0, 10), size = 10, replace = False)
X = x.reshape(2,5)

In [21]:
X

array([[8, 2, 1, 5, 9],
       [4, 0, 3, 7, 6]])

In [22]:
print(np.max(X, axis = 0)) # max value of each column
print(np.max(X, axis = 1)) # max value of each row

[8 2 3 7 9]
[9 7]


In [25]:
print(np.sum(X, axis = 0)) # sum of each column
print(np.sum(X, axis = 1)) # sum of each row

[12  2  4 12 15]
[25 20]


In [26]:
np.repeat(X, 3, axis = 0) # repeat each row 3 times

array([[8, 2, 1, 5, 9],
       [8, 2, 1, 5, 9],
       [8, 2, 1, 5, 9],
       [4, 0, 3, 7, 6],
       [4, 0, 3, 7, 6],
       [4, 0, 3, 7, 6]])

In [27]:
np.repeat(X, 3, axis = 1) # repeat each column 3 times

array([[8, 8, 8, 2, 2, 2, 1, 1, 1, 5, 5, 5, 9, 9, 9],
       [4, 4, 4, 0, 0, 0, 3, 3, 3, 7, 7, 7, 6, 6, 6]])

In [28]:
a = np.array([[ 0.0, 0.0, 0.0],
[10.0, 10.0, 10.0],
[20.0, 20.0, 20.0],
[30.0, 30.0, 30.0]])

In [29]:
b = np.array([1.0, 2.0, 3.0])

In [30]:
print(a.shape)
print(b.shape)

(4, 3)
(3,)


In [31]:
a+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [37]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b
# a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [36]:
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [34]:
a[:, np.newaxis].shape

(4, 1)

# 상관관계 분석

In [1]:
import pandas as pd
from scipy.stats import pearsonr

In [19]:
data = pd.read_csv(r'./data/파이썬_실습_1107.csv')
df = pd.DataFrame(data)

In [20]:
df

지자체       빈집   범죄발생건수
0     서울특별시  100,706  274,830
1     부산광역시  110,500  113,558
2     대구광역시   43,086   72,339
3     인천광역시   72,036   85,432
4     광주광역시   39,205   44,610
5     대전광역시   26,262   41,921
6     울산광역시   29,569   23,463
7   세종특별자치시   12,388    6,147
8       경기도  262,266  388,004
9       강원도   80,609   45,398
10     충청북도   68,843   47,020
11     충청남도  101,637   63,290
12     전라북도   90,190   52,587
13     전라남도  119,711   60,205
14     경상북도  127,459   75,300
15     경상남도  134,925  111,102
16  제주특별자치도   32,162   26,499

In [21]:
df = df.replace(',','', regex=True)
df = df.astype({'빈집':'float'})
df = df.astype({'범죄발생건수':'float'})

In [22]:
df

지자체        빈집    범죄발생건수
0     서울특별시  100706.0  274830.0
1     부산광역시  110500.0  113558.0
2     대구광역시   43086.0   72339.0
3     인천광역시   72036.0   85432.0
4     광주광역시   39205.0   44610.0
5     대전광역시   26262.0   41921.0
6     울산광역시   29569.0   23463.0
7   세종특별자치시   12388.0    6147.0
8       경기도  262266.0  388004.0
9       강원도   80609.0   45398.0
10     충청북도   68843.0   47020.0
11     충청남도  101637.0   63290.0
12     전라북도   90190.0   52587.0
13     전라남도  119711.0   60205.0
14     경상북도  127459.0   75300.0
15     경상남도  134925.0  111102.0
16  제주특별자치도   32162.0   26499.0

In [23]:
corr, p_value = pearsonr(df['빈집'], df['범죄발생건수'])
print(f"피어슨 상관계수: {corr}")
print(f"p-value: {p_value}")

if p_value < 0.05:
  print("유의미한 상관관계가 있습니다.")
else:
  print("유의미한 상관관계가 없습니다.")

피어슨 상관계수: 0.8057134112362629
p-value: 9.456242440166585e-05
유의미한 상관관계가 있습니다.
